### ISSUE TITLE
Understanding how redirect works 

### ISSUE THREAD

**Issue by bobo-romania** [scith/redirect_ynh#1]
Hi, 
I would like some information about how redirect_ynh works. 
From what I understood, this app allows you to have a web acces to a dockerised app. 

Here is my problem
I installed the official odoo container: https://registry.hub.docker.com/_/odoo/

Then, when I try to use redirect I'm having error messages
Here is what I tried to to do.
```
Choisissez un domaine pour la redirection: MYHOST.noho.st
Choisissez un chemin pour la redirection: /odoo
(Optionnel) Choisissez le port qui sera redirigé": 8069
(Optionnel) Choisissez le chemin qui sera redirigé":127.0.0.1
 ```
I'm having this message
 ```
Error: Unable to install the app on this location
+ echo 'Path not available: 127.0.0.1'
Path not available: 127.0.0.1
 ```

I'm doing something wrong but I don't really get what.

Can you explain / give an example about it ? 
Thanks.

**Comment by scith** [comment]
Hello,
Domain: your target domain
Path: your target path
(Optional) port: your source port
(Optional path: your source path

So in your case your source path should be set to "none". This way it will redirect http://127.0.0.1:8069/ to MYHOST.noho.st/odoo

The optional source path is there in case you had something like http://127.0.0.1:8069/odoo you would like to redirect (so a port AND a path to redirect).

However, the redirection made by this app is standardized in order to accomodate a variety of situations but needs to adapted in some. And Odoo is one of these... I can't get the Odoo container to work with the standard nginx file at the moment :(
But I would be interested in having an Odoo container as well so I'll keep you posted (or even make a dockerized Odoo app) once I found how to redirect it properly. Or please let me know if you find it before :)

Thanks

**Comment by scith** [comment]
OK it works!!!
But you HAVE TO set the target path to "/" (the root)
For example you could set a subdomain "odoo.domain.tld" and use redirect_ynh with the following options:
Domain: odoo.domain.tld
Path: /
Protect: Yes or No
Port: 8069
Path: none

And then go to odoo.domain.tld and that's it :)

**Comment by scith** [comment]
I made a first draft of a Dockerized Odoo app if needed: https://github.com/scith/docker_odoo_ynh
